sudo: false
language: android
jdk: oraclejdk8
android:
    components:
        - tools
        # The BuildTools version used by your project
        - build-tools-23.0.3

        # The SDK version used to compile your project
        - android-23

        # Additional components
        - extra-google-m2repository
        - extra-android-m2repository

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-21

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
      - ./gradlew app:test
      - ./gradlew app:connectedAndroidTest

before_install:
        - chmod +x gradlew

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
  - ./imgurbash.sh screen.png
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_success:
        - ./gradlew jacocoFullReport
        - bash <(curl -s https://codecov.io/bash)