sudo: false
language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-google-m2repository
        - extra-android-m2repository
#script: ./gradlew testDebugUnitTest jacocoTestDebugUnitTestReport
script: ./gradlew app:test jacocoTestDebugUnitTestReport
script: ./gradlew app:connectedAndroidTest jacocoTestDebugUnitTestReport
before_install:
        - chmod +x gradlew
after_success:
        - bash <(curl -s https://codecov.io/bash)