sudo: false
language: android
jdk: oraclejdk8
env:
  global:
    ADB_INSTALL_TIMEOUT=12 # minutes (2 minutes by default) - to avoid ShellCommandUnresponsiveException on travis
android:
    components:
        - tools
        # The BuildTools version used by your project
        - build-tools-23.0.3

        # The SDK version used to compile your project
        - android-23

        # Additional components
        - extra-google-m2repository
        - extra-android-m2repository

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-22

# Emulator Management: Create, Start and Wait
before_script:
      - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window &

script:
      - ./gradlew app:test jacocoTestDebugUnitTestReport
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      - ./gradlew app:connectedAndroidTest

before_install:
        - chmod +x gradlew

# after_success: - Moved to circle ci
  #      - bash <(curl -s https://codecov.io/bash)